name: CI

on:
  push:
    branches: [ main ]
    
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3.6.0
        with:
          java-version: 1.8
                
      - name: cache maven dependences
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
        
      - name: compile
        run: |
          cd bbq-back-end
          mvn compile
        
      - name: package
        run: |
          cd bbq-back-end
          mvn -B package --file pom.xml -Dmaven.test.skip=true
        
      - name: copy dist file with scp
        uses: appleboy/scp-action@master
        with: 
          host: ${{secrets.HOST}}
          username: root
          password: ${{secrets.PASSWORD}}
          port: 22
          source: "bbq-back-end"
          target: "/root"
          rm: false
          
