name: CI

on:
  push:
    branches: [ main ]
    
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8.0.345+1
          distribution: 'adopt'
                
      - name: cache maven dependences
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
        
      - name: compile
        run: |
          cd bbq-back-end
          mvn compile
        
      - name: package
        run: |
          cd bbq-back-end
          mvn -B package --file pom.xml -Dmaven.test.skip=true
        
      - name: copy jar file with scp
        uses: appleboy/scp-action@master
        with: 
          host: ${{secrets.HOST}}
          username: root
          password: ${{secrets.PASSWORD}}
          port: 22
          source: "bbq-back-end/target"
          target: "/root"
          rm: false
        
      - name: deploy back end
        uses: appleboy/ssh-action@master
        with: 
          host: ${{secrets.HOST}}
          username: root
          password: ${{secrets.PASSWORD}}
          script: |
            rm -rf /home/docker/bbq-1.0.0-SNAPSHOT.jar
            cp -r /root/bbq-back-end/target/bbq-1.0.0-SNAPSHOT.jar /home/docker/
            rm -rf /root/bbq-back-end
            cd /home/docker/
            docker-compose kill bbq
            docker-compose rm -f
            docker rmi -f $(docker images bbq:latest -q)
            docker-compose up -d --no-recreate
            
